// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAts0wI8-eD8SghojPJ3HOlRcWqIZQdwjQ',
    appId: '1:754521219990:web:37e51f3f418729916df3b7',
    messagingSenderId: '754521219990',
    projectId: 'grocery-2022',
    authDomain: 'grocery-2022.firebaseapp.com',
    storageBucket: 'grocery-2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZB7S-ea47H79Up-9h8J2MCahGPPpfOBg',
    appId: '1:754521219990:android:9373e5a6b7630ad66df3b7',
    messagingSenderId: '754521219990',
    projectId: 'grocery-2022',
    storageBucket: 'grocery-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpZ5mqn0QNExduU2w6uJArfWwDC1Lykjw',
    appId: '1:754521219990:ios:fa1c1d144b1dc0b16df3b7',
    messagingSenderId: '754521219990',
    projectId: 'grocery-2022',
    storageBucket: 'grocery-2022.appspot.com',
    iosClientId: '754521219990-78ajo9atvn86nn0g42n0dsghf03tl7cp.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp2022',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpZ5mqn0QNExduU2w6uJArfWwDC1Lykjw',
    appId: '1:754521219990:ios:fa1c1d144b1dc0b16df3b7',
    messagingSenderId: '754521219990',
    projectId: 'grocery-2022',
    storageBucket: 'grocery-2022.appspot.com',
    iosClientId: '754521219990-78ajo9atvn86nn0g42n0dsghf03tl7cp.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp2022',
  );
}
